import Class as C

car_info_dict = {
    "Car1" : {
        "brand" : C.CarBrand.Aston_martin ,
        "release_year" : "2005",
        "seats" : "4",
        "doors" : "4",
        "gear_type" : C.GearType.Auto,
        "fuel_type" : C.FuelType.Benzien,
        "distance" : "5049",
        "gps_type" : C.GPSType.NoneGPS,
        "color" : "Black",
        "features" : "Automatic_seat",
        "info" : "",
        "images" : "",
        "price" : "3000",
        "carstatus" : "Available",
        "review" : ""
    },
    "Car2" : {
        "brand" : C.CarBrand.Audi,
        "release_year" : "2010",
        "seats" : "4",
        "doors" : "4",
        "gear_type" : C.GearType.Auto,
        "fuel_type" : C.FuelType.Benzien,
        "distance" : "12654",
        "gps_type" : C.GPSType.NoneGPS,
        "color" : "Black",
        "features" : "",
        "info" : "",
        "images" : "",
        "price" : "3500",
        "carstatus" : "Available",
        "review" : ""
    },
    "Car3" : {
        "brand" : C.CarBrand.BMW,
        "release_year" : "2009",
        "seats" : "4",
        "doors" : "4",
        "gear_type" : C.GearType.Auto,
        "fuel_type" : C.FuelType.Benzien,
        "distance" : "9801",
        "gps_type" : C.GPSType.CarTrack,
        "color" : "White",
        "features" : "Bluetooth_Music",
        "info" : "",
        "images" : "",
        "price" : "4000",
        "carstatus" : "Available",
        "review" : "GOOD JOB"
    },
    "Car4" : {
        "brand" : C.CarBrand.BYD,
        "release_year" : "2020",
        "seats" : "4",
        "doors" : "4",
        "gear_type" : C.GearType.Auto,
        "fuel_type" : C.FuelType.EV,
        "distance" : "1500",
        "gps_type" : C.GPSType.Otoplug,
        "color" : "blonde",
        "features" : "",
        "info" : "",
        "images" : "",
        "price" : "2500",
        "carstatus" : "Available",
        "review" : ""
    },
    "Car5" : {
        "brand" : C.CarBrand.Chevrolet,
        "release_year" : "2006",
        "seats" : "4",
        "doors" : "4", 
        "gear_type" : C.GearType.Auto,
        "fuel_type" : C.FuelType.Benzien,
        "distance" : "15602",
        "gps_type" : C.GPSType.NoneGPS,
        "color" : "Yellow",
        "features" : "",
        "info" : "",
        "images" : "",
        "price" : "3999",
        "carstatus" : "Available",
        "review" : ""
    },
    "Car6" : {
        "brand" : C.CarBrand.Ford,
        "release_year" : "2004",
        "seats" : "7",
        "doors" : "4",
        "gear_type" : C.GearType.Manual,
        "fuel_type" : C.FuelType.Diesel,
        "distance" : "25040",
        "gps_type" : C.GPSType.NoneGPS,
        "color" : "Dark_Blue",
        "features" : "",
        "info" : "",
        "images" : "",
        "price" : "3000",
        "carstatus" : "Available",
        "review" : ""
    },
    "Car7" : {
        "brand" : C.CarBrand.Honda,
        "release_year" : "2011",
        "seats" : "4",
        "doors" : "4",
        "gear_type" : C.GearType.Auto,
        "fuel_type" : C.FuelType.Benzien,
        "distance" : "9800",
        "gps_type" : C.GPSType.Others, 
        "color" : "Gray",
        "features" : "",
        "info" : "",
        "images" : "",
        "price" : "1900",
        "carstatus" : "Available",
        "review" : ""
    },
    "Car8" : {
        "brand" : C.CarBrand.Hyundai, 
        "release_year" : "2012",
        "seats" : "10",
        "doors" : "4",
        "gear_type" : C.GearType.Auto,
        "fuel_type" : C.FuelType.Benzien,
        "distance" : "16094",
        "gps_type" : C.GPSType.NoneGPS,
        "color" : "Black",
        "features" : "LED SCREEN",
        "info" : "",
        "images" : "",
        "price" : "4599",
        "carstatus" : "Available",
        "review" : ""
    },
    "Car9" : {
        "brand" : C.CarBrand.Isuzu, 
        "release_year" : "2005",
        "seats" : "4",
        "doors" : "2",
        "gear_type" : C.GearType.Manual,
        "fuel_type" : C.FuelType.Diesel,
        "distance" : "30071",
        "gps_type" : C.GPSType.Others,
        "color" : "White",
        "features" : "",
        "info" : "",
        "images" : "",
        "price" : "2990",
        "carstatus" : "Available",
        "review" : ""
    },
    "Car10" : {
        "brand" : C.CarBrand.Lamborgini,
        "release_year" : "2015",
        "seats" : "2",
        "doors" : "2",
        "gear_type" : C.GearType.Manual,
        "fuel_type" : C.FuelType.Benzien,
        "distance" : "3540",
        "gps_type" : C.GPSType.NoneGPS,
        "color" : "Red",
        "features" : "",
        "info" : "",
        "images" : "",
        "price" : "15000",
        "carstatus" : "Available",
        "review" : ""
    },
    "Car11" : {
        "brand" : C.CarBrand.MG, 
        "release_year" : "2018",
        "seats" : "7",
        "doors" : "4",
        "gear_type" : C.GearType.Auto,
        "fuel_type" : C.FuelType.Benzien,
        "distance" : "14200",
        "gps_type" : C.GPSType.Others,
        "color" : "Yellow",
        "features" : "",
        "info" : "",
        "images" : "",
        "price" : "2600",
        "carstatus" : "Available",
        "review" : "",
    },
    "Car12" : {
        "brand" : C.CarBrand.Nissan,
        "release_year" : "2009",
        "seats" : "4",
        "doors" : "4",
        "gear_type" : C.GearType.Auto,
        "fuel_type" : C.FuelType.Benzien,
        "distance" : "18005",
        "gps_type" : C.GPSType.Eyefleet,
        "color" : "Purple",
        "features" : "",
        "info" : "",
        "images" : "",
        "price" : "2099",
        "carstatus" : "Available",
        "review" : "",
    }
}

Car_instance_list = []
for i in car_info_dict:
    Car_instance_list.append(C.Car(**car_info_dict))